name: frontend-tests-and-coverage

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # to add comments to the PRs
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      
      # 1. RUN ONLY TESTS ON PUSH
      - name: Run frontend tests
        if: github.event_name == 'push'
        run: npm test
        working-directory: frontend
        
      # 2. RUN COVERAGE ON PRs
      - name: Run jest with coverage
        if: github.event_name == 'pull_request'
        run: npx jest --coverage --coverageReporters json-summary
        working-directory: frontend

      # 3. POST COMMENT ON PR
      - name: Jest Coverage Comment
        if: >
          github.event_name == 'pull_request'
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./frontend/coverage/coverage-summary.json
          title: Frontend Coverage Report
